### ISSUE TITLE
I am getting the following error

### ISSUE THREAD

**Issue by dheerajbred** [ndrwpvlv/pym3u8#1]
I am getting the following error
```

E:\Flutter Apps\Downloads exper\a\pym3u8>python -m pym3u8 -u "https://up.imgupio.com/demo/birds.m3u8" -p "socks5://127.0.0.1:1080"
-----------------
pym3u8. Stream and video downloader
-----------------

Variables:
url: https://up.imgupio.com/demo/birds.m3u8
referer:
filename: file
extension: ts
user_agent: WebHTML5Player/1.0.0
proxy: socks5://127.0.0.1:1080
m3u8_ext: m3u8
ssl_verify: False
max_retries: 5
-----------------

Traceback (most recent call last):
  File "E:\Installs\Python\Python38-32\lib\site-packages\socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\contrib\socks.py", line 90, in _new_conn
    conn = socks.create_connection(
  File "E:\Installs\Python\Python38-32\lib\site-packages\socks.py", line 209, in create_connection
    raise err
  File "E:\Installs\Python\Python38-32\lib\site-packages\socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "E:\Installs\Python\Python38-32\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "E:\Installs\Python\Python38-32\lib\site-packages\socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 300, in connect
    conn = self._new_conn()
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\contrib\socks.py", line 121, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0311ADA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Installs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 747, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "E:\Installs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='up.imgupio.com', port=443): Max retries exceeded with url: /demo/birds.m3u8 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0311ADA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Installs\Python\Python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Installs\Python\Python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\Flutter Apps\Anime Prime\Downloads exper\a\pym3u8\pym3u8\__main__.py", line 52, in <module>
    main()
  File "E:\Flutter Apps\Anime Prime\Downloads exper\a\pym3u8\pym3u8\__main__.py", line 48, in main
    loader.download()
  File "E:\Flutter Apps\Anime Prime\Downloads exper\a\pym3u8\pym3u8\loader.py", line 70, in download
    self.playlist = self.get_playlist()
  File "E:\Flutter Apps\Anime Prime\Downloads exper\a\pym3u8\pym3u8\loader.py", line 37, in get_playlist
    response = self.session.get(self.url, verify=self.ssl_verify, headers={
  File "E:\Installs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "E:\Installs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Installs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "E:\Installs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='up.imgupio.com', port=443): Max retries exceeded with url: /demo/birds.m3u8 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x0311ADA8>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```

**Comment by ndrwpvlv** [comment]
Hello. The error showed fail with proxy connection. Have you installed proxy on your machine?
